
service: yrtt-tasks-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
  apiGateway:
    shouldStartNameWithService: true

package:
  artifact: target/tasks-api-java-dev.jar

functions:
  get-tasks-java-api:
    handler: com.techreturners.GetTasksHandler
    events:
      - http:
          path: /users/{userID}/tasks
          method: get

  save-tasks-java-api:
    handler: com.techreturners.SaveTasksHandler
    events:
      - http:
          path: /users/{userID}/tasks
          method: post
